
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQ FUN FUNCION GT IDENTIFICADOR IGUAL IMP INCREMENTO LBRACE LBRACKET LPAREN LT MALPH NUMERO PUNTOYCOMA RBRACE RBRACKET RPAREN STRING TIPO VI WAR\n        program : expression\n                | program expression\n        \n        expression : variable_declaration\n                   | variable_assignment\n                   | main_function\n                   | function_definition\n                   | if_statement\n                   | while_statement\n                   \n                   \n        \n        main_function : FUN MALPH LBRACKET RBRACKET LPAREN imp_statement RPAREN\n        \n        function_definition : FUN FUNCION LBRACKET RBRACKET LPAREN imp_statement RPAREN\n        \n        imp_statement : IMP IDENTIFICADOR PUNTOYCOMA\n                    | IMP PUNTOYCOMA\n        \n        variable_declaration : IDENTIFICADOR PUNTOYCOMA TIPO IGUAL valor\n                             | IDENTIFICADOR PUNTOYCOMA TIPO\n        \n        variable_assignment : IDENTIFICADOR PUNTOYCOMA TIPO IGUAL valor\n        \n        valor : NUMERO\n              | STRING\n        \n        if_statement : VI LBRACE condition RBRACE LPAREN imp_statement RPAREN\n        \n        condition : IDENTIFICADOR GT IDENTIFICADOR\n                  | IDENTIFICADOR GT NUMERO\n                  | NUMERO GT IDENTIFICADOR\n                  | IDENTIFICADOR LT IDENTIFICADOR\n                  | IDENTIFICADOR LT NUMERO\n                  | NUMERO LT IDENTIFICADOR\n                  | IDENTIFICADOR EQ IDENTIFICADOR\n                  | IDENTIFICADOR EQ NUMERO\n                  | NUMERO EQ IDENTIFICADOR\n        \n        while_statement : WAR LBRACE condition RBRACE LPAREN imp_statement INCREMENTO IDENTIFICADOR PUNTOYCOMA RPAREN\n        '
    
_lr_action_items = {'IDENTIFICADOR':([0,1,2,3,4,5,6,7,8,13,17,18,19,30,31,32,33,34,35,37,38,39,54,58,61,62,63,67,],[9,9,-1,-3,-4,-5,-6,-7,-8,-2,23,23,-14,43,45,47,49,50,51,-13,-16,-17,59,-9,-10,-18,65,-28,]),'FUN':([0,1,2,3,4,5,6,7,8,13,19,37,38,39,58,61,62,67,],[10,10,-1,-3,-4,-5,-6,-7,-8,-2,-14,-13,-16,-17,-9,-10,-18,-28,]),'VI':([0,1,2,3,4,5,6,7,8,13,19,37,38,39,58,61,62,67,],[11,11,-1,-3,-4,-5,-6,-7,-8,-2,-14,-13,-16,-17,-9,-10,-18,-28,]),'WAR':([0,1,2,3,4,5,6,7,8,13,19,37,38,39,58,61,62,67,],[12,12,-1,-3,-4,-5,-6,-7,-8,-2,-14,-13,-16,-17,-9,-10,-18,-28,]),'$end':([1,2,3,4,5,6,7,8,13,19,37,38,39,58,61,62,67,],[0,-1,-3,-4,-5,-6,-7,-8,-2,-14,-13,-16,-17,-9,-10,-18,-28,]),'PUNTOYCOMA':([9,54,59,65,],[14,60,64,66,]),'MALPH':([10,],[15,]),'FUNCION':([10,],[16,]),'LBRACE':([11,12,],[17,18,]),'TIPO':([14,],[19,]),'LBRACKET':([15,16,],[20,21,]),'NUMERO':([17,18,26,30,31,32,],[24,24,38,44,46,48,]),'IGUAL':([19,],[26,]),'RBRACKET':([20,21,],[27,28,]),'RBRACE':([22,25,43,44,45,46,47,48,49,50,51,],[29,36,-19,-20,-22,-23,-25,-26,-21,-24,-27,]),'GT':([23,24,],[30,33,]),'LT':([23,24,],[31,34,]),'EQ':([23,24,],[32,35,]),'STRING':([26,],[39,]),'LPAREN':([27,28,29,36,],[40,41,42,52,]),'IMP':([40,41,42,52,],[54,54,54,54,]),'RPAREN':([53,55,56,60,64,66,],[58,61,62,-12,-11,67,]),'INCREMENTO':([57,60,64,],[63,-12,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expression':([0,1,],[2,13,]),'variable_declaration':([0,1,],[3,3,]),'variable_assignment':([0,1,],[4,4,]),'main_function':([0,1,],[5,5,]),'function_definition':([0,1,],[6,6,]),'if_statement':([0,1,],[7,7,]),'while_statement':([0,1,],[8,8,]),'condition':([17,18,],[22,25,]),'valor':([26,],[37,]),'imp_statement':([40,41,42,52,],[53,55,56,57,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> expression','program',1,'p_program','analizadorLexico.py',101),
  ('program -> program expression','program',2,'p_program','analizadorLexico.py',102),
  ('expression -> variable_declaration','expression',1,'p_expression','analizadorLexico.py',111),
  ('expression -> variable_assignment','expression',1,'p_expression','analizadorLexico.py',112),
  ('expression -> main_function','expression',1,'p_expression','analizadorLexico.py',113),
  ('expression -> function_definition','expression',1,'p_expression','analizadorLexico.py',114),
  ('expression -> if_statement','expression',1,'p_expression','analizadorLexico.py',115),
  ('expression -> while_statement','expression',1,'p_expression','analizadorLexico.py',116),
  ('main_function -> FUN MALPH LBRACKET RBRACKET LPAREN imp_statement RPAREN','main_function',7,'p_main_function','analizadorLexico.py',124),
  ('function_definition -> FUN FUNCION LBRACKET RBRACKET LPAREN imp_statement RPAREN','function_definition',7,'p_function_definition','analizadorLexico.py',132),
  ('imp_statement -> IMP IDENTIFICADOR PUNTOYCOMA','imp_statement',3,'p_imp_statement','analizadorLexico.py',147),
  ('imp_statement -> IMP PUNTOYCOMA','imp_statement',2,'p_imp_statement','analizadorLexico.py',148),
  ('variable_declaration -> IDENTIFICADOR PUNTOYCOMA TIPO IGUAL valor','variable_declaration',5,'p_variable_declaration','analizadorLexico.py',163),
  ('variable_declaration -> IDENTIFICADOR PUNTOYCOMA TIPO','variable_declaration',3,'p_variable_declaration','analizadorLexico.py',164),
  ('variable_assignment -> IDENTIFICADOR PUNTOYCOMA TIPO IGUAL valor','variable_assignment',5,'p_variable_assignment','analizadorLexico.py',175),
  ('valor -> NUMERO','valor',1,'p_valor','analizadorLexico.py',190),
  ('valor -> STRING','valor',1,'p_valor','analizadorLexico.py',191),
  ('if_statement -> VI LBRACE condition RBRACE LPAREN imp_statement RPAREN','if_statement',7,'p_if_statement','analizadorLexico.py',197),
  ('condition -> IDENTIFICADOR GT IDENTIFICADOR','condition',3,'p_condition','analizadorLexico.py',208),
  ('condition -> IDENTIFICADOR GT NUMERO','condition',3,'p_condition','analizadorLexico.py',209),
  ('condition -> NUMERO GT IDENTIFICADOR','condition',3,'p_condition','analizadorLexico.py',210),
  ('condition -> IDENTIFICADOR LT IDENTIFICADOR','condition',3,'p_condition','analizadorLexico.py',211),
  ('condition -> IDENTIFICADOR LT NUMERO','condition',3,'p_condition','analizadorLexico.py',212),
  ('condition -> NUMERO LT IDENTIFICADOR','condition',3,'p_condition','analizadorLexico.py',213),
  ('condition -> IDENTIFICADOR EQ IDENTIFICADOR','condition',3,'p_condition','analizadorLexico.py',214),
  ('condition -> IDENTIFICADOR EQ NUMERO','condition',3,'p_condition','analizadorLexico.py',215),
  ('condition -> NUMERO EQ IDENTIFICADOR','condition',3,'p_condition','analizadorLexico.py',216),
  ('while_statement -> WAR LBRACE condition RBRACE LPAREN imp_statement INCREMENTO IDENTIFICADOR PUNTOYCOMA RPAREN','while_statement',10,'p_while_statement','analizadorLexico.py',253),
]
